[clients]
machine1 ansible_host=10.0.0.1
machine2 ansible_host=10.0.0.2

[serveur]
serveur_nfs ansible_host=10.0.0.100

[switchs]
switch1 ansible_host=10.0.0.11
switch2 ansible_host=10.0.0.12
switch3 ansible_host=10.0.0.13

[linux:children]
clients
serveur

[linux:vars]
ansible_user=ansible
ansible_become=yes

[switchs:vars]
ansible_user=cumulus
ansible_become=yes
ansible_ssh_pass=cumulus
