---
- hosts: switch1,switch2
  gather_facts: no
  roles:
    - cumulus_l2

- hosts: switch3
  gather_facts: no
  roles:
    - cumulus_l3

- hosts: serveur_nfs
  roles:
    - bonding_serveur
    - nfs_serveur

- hosts: machine1,machine2
  roles:
    - nfs_client
