- name: Déploiement du Serveur NFS
  hosts: serveur
  become: yes
  roles:
    - nfs_serveur

- name: Déploiement du Serveur NFS
  hosts: serveur
  become: yes
  roles:
    - bonding_serveur
    - nfs_serveur

- name: Configuration des Clients NFS
  hosts: clients
  become: yes
  roles:
    - nfs_client
