---
# tasks file for config_clag

- name: Déployer /etc/network/interfaces sur switch1
  copy:
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    content: |
      auto lo
      iface lo inet loopback

      auto eth0
      iface eth0
          address 10.0.0.51/24
          vrf mgmt

      # Nouveau lien vers Switch 4
      auto eth1
      iface eth1

      auto peerlink
      iface peerlink
          bond-slaves swp4 swp5

      auto bond-m1
      iface bond-m1
          bond-slaves swp1
          clag-id 1
          bridge-access 10

      auto bond-m2
      iface bond-m2
          bond-slaves swp2
          clag-id 2
          bridge-access 20

      auto bridge
      iface bridge
          bridge-ports peerlink bond-m1 bond-m2 swp3 eth1
          bridge-vlan-aware yes
          bridge-vids 10 20

      auto peerlink.4094
      iface peerlink.4094
          clagd-peer-ip linklocal
          clagd-sys-mac 44:38:39:FF:00:01
          clagd-priority 1000
          clagd-backup-ip 10.0.0.52 vrf mgmt

      auto mgmt
      iface mgmt
          address 127.0.0.1/8
          address ::1/128
          vrf-table auto
  when: inventory_hostname == "switch1"

- name: Déployer /etc/network/interfaces sur switch2
  copy:
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    content: |
      auto lo
      iface lo inet loopback

      auto eth0
      iface eth0
          address 10.0.0.52/24
          vrf mgmt

      # Nouveau lien vers Switch 4
      auto eth1
      iface eth1

      auto peerlink
      iface peerlink
          bond-slaves swp4 swp5

      auto bond-m1
      iface bond-m1
          bond-slaves swp1
          clag-id 1
          bridge-access 10

      auto bond-m2
      iface bond-m2
          bond-slaves swp2
          clag-id 2
          bridge-access 20

      auto bridge
      iface bridge
          bridge-ports peerlink bond-m1 bond-m2 swp3 eth1
          bridge-vlan-aware yes
          bridge-vids 10 20

      auto peerlink.4094
      iface peerlink.4094
          clagd-peer-ip linklocal
          clagd-sys-mac 44:38:39:FF:00:01
          clagd-priority 2000
          clagd-backup-ip 10.0.0.51 vrf mgmt

      auto mgmt
      iface mgmt
          address 127.0.0.1/8
          address ::1/128
          vrf-table auto
  when: inventory_hostname == "switch2"

- name: Appliquer la configuration réseau Cumulus
  shell: ifreload -a
  args:
    executable: /bin/bash

- name: Vérifier la config CLAG
  shell: |
    net show configuration commands
    echo "----------------"
    clagctl
    echo "----------------"
    bridge vlan show
    echo "----------------"
    ip a
  args:
    executable: /bin/bash
  register: clag_check
  changed_when: false

- name: Afficher la vérification CLAG
  debug:
    var: clag_check.stdout
