[machines]
machine1 ansible_host=10.0.0.21
machine2 ansible_host=10.0.0.22
machine3 ansible_host=10.0.0.23

[machines:vars]
ansible_user=debian
ansible_ssh_pass=debian
ansible_become_pass=debian

[switchs]
switch1 ansible_host=10.0.0.31
switch2 ansible_host=10.0.0.32
switch3 ansible_host=10.0.0.33

[switchs:vars]
ansible_user=cumulus
ansible_ssh_pass=testtesttest
ansible_become_pass=testtesttest
