---
- name: Configurer Switch 3 via NCLU
  shell: |
    net add bridge bridge vids 10,20 || true
    net add interface swp1 bridge vids 10,20 || true
    net add interface swp2 bridge vids 10,20 || true
    net add vlan 10 ip address 192.168.1.254/24 || true
    net add vlan 20 ip address 192.168.2.254/24 || true
    net commit || true
  args:
    executable: /bin/bash
  register: nclu_config
  changed_when: true

- name: Afficher le résultat NCLU
  debug:
    var: nclu_config.stdout_lines

- name: Vérifier la configuration du switch 3
  shell: |
    net show configuration
    echo "----------------"
    ip a
    echo "----------------"
    bridge vlan show
  args:
    executable: /bin/bash
  register: sw3_check
  changed_when: false

- name: Afficher la vérification de switch3
  debug:
    var: sw3_check.stdout
