[clag_switches]
switch1 ansible_host=10.0.0.51 clag_priority=1000 clag_backup_ip=10.0.0.52
switch2 ansible_host=10.0.0.52 clag_priority=2000 clag_backup_ip=10.0.0.51

[routeurs]
switch3 ansible_host=10.0.0.53

[machines]
machine1 ansible_host=10.0.0.41
machine2 ansible_host=10.0.0.42

[clag_switches:vars]
ansible_user=cumulus
ansible_ssh_pass=testtesttest

[routeurs:vars]
ansible_user=cumulus
ansible_ssh_pass=testtesttest

[machines:vars]
ansible_user=root
ansible_ssh_pass=root
