- hosts: clag_switches
  become: true
  gather_facts: no
  roles:
    - config_clag

- hosts: machines
  become: true
  gather_facts: no
  roles:
    - config_bonding_machines

- hosts: switch3
  become: true
  gather_facts: no
  roles:
    - config_routage_sw3

- hosts: switch4
  become: true
  gather_facts: no
  roles:
    - Routeur2
