- name: Installer des outils de base
  hosts: clients
  become: yes
  tasks:
    - name: Installer vim, curl et net-tools
      apt:
        name:
          - vim
          - curl
          - net-tools
        state: present
        update_cache: yes
