---
- name: Configurer l'IP sur ens34 pour machine1
  copy:
    dest: /etc/network/interfaces.d/ens34
    content: |
      auto ens34
      iface ens34 inet static
          address 192.168.10.21
          netmask 255.255.255.0
  when: inventory_hostname == "machine1"

- name: Configurer l'IP sur ens34 pour machine2
  copy:
    dest: /etc/network/interfaces.d/ens34
    content: |
      auto ens34
      iface ens34 inet static
          address 192.168.10.22
          netmask 255.255.255.0
  when: inventory_hostname == "machine2"

- name: Configurer l'IP sur ens34 pour machine3
  copy:
    dest: /etc/network/interfaces.d/ens34
    content: |
      auto ens34
      iface ens34 inet static
          address 192.168.10.23
          netmask 255.255.255.0
  when: inventory_hostname == "machine3"

- name: Supprimer les anciennes IP de ens34
  command: ip addr flush dev ens34

- name: Appliquer l'IP sur ens34 pour machine1
  command: ip addr add 192.168.10.21/24 dev ens34
  when: inventory_hostname == "machine1"

- name: Appliquer l'IP sur ens34 pour machine2
  command: ip addr add 192.168.10.22/24 dev ens34
  when: inventory_hostname == "machine2"

- name: Appliquer l'IP sur ens34 pour machine3
  command: ip addr add 192.168.10.23/24 dev ens34
  when: inventory_hostname == "machine3"

- name: Activer ens34
  command: ip link set ens34 up
